language_de = {
'trayMenuClose' : "Beenden",
'error' : "Fehler",
'errorMessage' : "Entschuldigung, es ist leider ein Fehler aufgeteten.",
'couldntFindBackend' : "Konnte das Backend nicht laden.",
'add' : "Hinzufuegen",
'del' : "Loeschen",
'filename' : "Dateiname",
'target' : "Einhaengepunkt",
'pwd' : "Passwort",
'none' : "(keine)", #Please use "()"
'cont' : "Container",
'pathToContainer' : "Pfad zum Container",
'savePwd' : "Passwort speichern",
'mountOpt' : "Optionen",
'createNewContainer' : "Neuen Container erstellen",
'addExistingContainer' : "Schon existierenden Container hinzufuegen",
'addContainer' : "Container hinzufuegen",
'userMount' : "Fuer normale Nutzer zugaenglich machen",
'mount' : "Einbinden",
'addMode' : "Sie habe nun folgende Moeglichkeiten:\nWenn Sie einen neuen Container erstellen moechten, waehlen Sie bitte den ersten Eintrag.\nWenn Sie einen schon bestehenden Container hinzufuegen wollen, waehlen Sie den zweiten.",
'createNewPath' : "Bitte waehlen Sie den Dateinamen des neuen Containers und bestimmen Sie den Ort, wo der Container abgelegt werden soll.\nWenn Sie eine ganze Partition verschluesseln wollen, dann geben Sie als Dateinamen bitte die Geraetedatei von dieser an und als Pfad den Pfad zu dieser Datei.",
'addExistingPath' : "Bitte waehlen Sie nun den Container aus, den Sie der Liste hinzufuegen wollen!",
'addExistingTarget' : "Geben Sie nun an, ob der Order, in dem der Container eingehaengt werden soll von gTrueCrypt erstellt werden soll, oder ob Sie ihn angeben wollen.\nDiese Einstellung koennen Sie jederzeit in der Hauptansicht des Containers aendern.",
'letCreate' : "Lasse gTC einen Einhaengepunkt erstellen",
'forward' : "Weiter",
'cancel' : "Abbrechen",
'useOwn' : "Eigenen Einhaengepunkt bestimmen",
'mainCouldNotGetContainerInfo' : "Fehler beim Laden der Container-Informationen"
}
